### ISSUE TITLE
<a> tags not impl

### ISSUE THREAD

**Issue by Mas0nShi** [capricorn86/happy-dom#413] opened 2022-03-16 09:45 UTC
example code:

```javascript
document.write(`<!doctype html>
<meta charset="windows-1252">
<a href="?sm&ouml;rg&aring;sbord" name="123">Test</a>`)
console.log(document.getElementsByName("123")[0].href);
// undefined

```

**Comment by capricorn86** [comment] 2022-03-27 00:36
Duplicate of #204

**Closed** 2022-03-27 00:36 UTC
Labels: enhancement
