### ISSUE TITLE
static get observedAttributes not being called for classes inheriting HTMLElement

### ISSUE THREAD

**Issue by jgonte** [capricorn86/happy-dom#117] opened 2020-10-14 10:41 UTC
https://developer.mozilla.org/en-US/docs/Web/Web_Components/Using_custom_elements

**Comment by capricorn86** [comment] 2020-10-16 00:27
@jgonte There is a unit test for this scenario and I was not able to reproduce this with the latest code. However, I have added an integration test to make sure that it works all the way. I also noticed that the HTMLElement class might not have been exported correctly.

Can you try with the latest code? If it does not work with that, can you please explain in more detail how the problem occurs?

**Comment by jgonte** [comment] 2020-10-16 13:29
Right now I am stuck with other things but as soon as I am done with those, I will look into the issue

Thank you so much
Jorge

________________________________

**Comment by capricorn86** [comment] 2020-11-10 14:59
@jgonte any news on the bugs you filed. I am unable to reproduce them :slightly_smiling_face: 

Is it possible that you where using an older version?

**Comment by jgonte** [comment] 2020-11-12 14:39
Most likely
I will update to the latest version and let you know 🙂

________________________________

**Comment by jgonte** [comment] 2020-11-12 15:13
Still getting the error: 🙁
TypeError: node.replaceWith is not a function

 |         (node as HTMLElement).replaceWith(newNode);         |                               ^

"@happy-dom/jest-environment": "^1.11.3",
    "@types/jest": "^26.0.8",
    "happy-dom": "^1.11.3",
    "jest": "^26.2.2",


________________________________

**Comment by capricorn86** [comment] 2020-11-12 16:26
@jgonte I think I found the problem. Text and comment nodes where not implementing the ChildNode interface, but according to spec they should. I have tested with HTMLElement's, that is why it worked for me.

Is "node" in your example a Text or Comment node?

I have fixed the problem for Text and Comment node now. Hopefully that solves the problem for you :slightly_smiling_face: 

You can read more about the release here:
https://github.com/capricorn86/happy-dom/releases/tag/v1.11.4

**Comment by jgonte** [comment] 2020-11-15 20:08
Below is the unit test I am using to test that it works
Since it is JavaScript I might be doing something wrong :-) but it looks observedAttributes is not being called

describe("custom element tests", () => {

    it('should define a custom element', () => {

        let calledFromObservedAttributes = false;

        // Define the component
        class MyComponent extends HTMLElement {

            static get observedAttributes() {

                calledFromObservedAttributes = true;

                return [];
            }
        }

        customElements.define('my-component', MyComponent);

        // Attach it to the DOM
        const root = document.createElement('div');

        root.innerHTML='<my-component></my-component>';

        document.body.appendChild(root);

        // Check that the methods were called
        expect(calledFromObservedAttributes).toEqual(true);        // Is still false
    });
});

**Comment by capricorn86** [comment] 2020-11-15 21:23
@jgonte "attributeChangedCallback()" has to be defined in order for "observedAttributes" to be called which was according to spec. However, "observedAttributes" should be called during "customElements.define()" and be called even if an attribute has not been set, which was not the case in Happy DOM. I have fixed it now :slightly_smiling_face: 

The following test works with the latest code:
```
it('should define a custom element', () => {
    let calledFromObservedAttributes = false;

    class MyComponent extends HTMLElement {

        static get observedAttributes() {
            calledFromObservedAttributes = true;

            return [];
        }

        attributeChangedCallback() {}
    }

    customElements.define('my-component', MyComponent);

    expect(calledFromObservedAttributes).toEqual(true);
});
```

Read more about the release:
https://github.com/capricorn86/happy-dom/releases/tag/v1.11.5

**Comment by jgonte** [comment] 2020-11-16 15:00
Very nice!
Excellent work ... again :-)

And thank you for pointing out my mistake!

**Comment by davidortnercybercom** [comment] 2020-11-16 20:36
Thanks! Nice to hear that it has been fixed! :slightly_smiling_face: 

Are there any open issues left or did the last fixes work?

**Comment by capricorn86** [comment] 2020-11-16 20:47
Thanks @jgonte! Nice to hear that it has been fixed! :slightly_smiling_face:

Are there any open issues left or did the last fixes work?

**Comment by jgonte** [comment] 2020-11-17 19:32
No as far as I know :-)

**Comment by capricorn86** [comment] 2020-11-18 19:37
Nice to hear! Then I can close this :slightly_smiling_face:

**Closed by capricorn86** 2020-11-18 19:37 UTC
