### ISSUE TITLE
Jsdom inconsistencies for 0px in matchInilneSnapshot

### ISSUE THREAD

**Issue by belgattitude** [capricorn86/happy-dom#922] opened 2023-05-14 10:03 UTC
**Describe the bug**

While experimenting a move from jsdom to happy-dom, I stumbled on a different way to express style in jsdom/happy-dom.

![image](https://github.com/capricorn86/happy-dom/assets/259798/b23df743-c6a2-48bf-a65c-6786dd95aa50)

**To Reproduce**

Don't know if it helps enough but you'll find info here: https://github.com/strapi/strapi/pull/16713#issuecomment-1546859997

Example test: https://github.com/strapi/strapi/blob/main/packages/core/admin/admin/src/pages/NotFoundPage/tests/index.test.js#L27

**Expected behavior**

I'm not sure if it should be changed in happy-dom, but for users migrating from jsdom it can certainly help.

**Additional context**

**Comment by capricorn86** [comment] 2023-05-15 12:39
Thank you for reporting @belgattitude! :slightly_smiling_face: 

Happy DOM aims to work according to spec and behave like a browser as much as possible. Happy DOM behaves according to spec here while JSDOM doesn't.

You can easily test it in dev tools in the browser:
```javascript
var element = document.createElement('div');
element.style.height = '0';

// Outputs: '<div style="height: 0px;"></div>'
console.log(element.outerHTML);
```

**Comment by capricorn86** [comment] 2023-05-15 12:40
I will close this issue as it is working as intended.

**Comment by capricorn86** [comment] 2023-05-15 21:43
Sorry @belgattitude. I think I was a bit to fast closing this one. Read the snapshot the other way around. I have re-opened it.

**Comment by belgattitude** [comment] 2023-05-15 22:23
Fantastic, thank you

**Comment by capricorn86** [comment] 2023-05-18 18:56
@belgattitude this has been fixed now.

You can read more about the release here:
https://github.com/capricorn86/happy-dom/releases/tag/v9.19.0

**Closed by capricorn86** 2023-05-18 18:56 UTC
Labels: bug

**Comment by belgattitude** [comment] 2023-05-22 21:13
Thank you so much @capricorn86 ... I'll test this out soon.
