### ISSUE TITLE
disabled attribute rendered with 'false' instead of ''

### ISSUE THREAD

**Issue by Ken-vdE** [capricorn86/happy-dom#578] opened 2022-09-06 12:04 UTC
The original issue can be found here: https://github.com/vuejs/test-utils/pull/1759

The disabled attribute gets set to 'false', which is incorrect.
The spec does not allow for false values, as per https://html.spec.whatwg.org/multipage/common-microsyntaxes.html#boolean-attributes.

The issue arises here (using Vue Test Utils):
```vue
<template>
   <component :is="type" :disabled="index > 1" @click="$emit('something')" data-testid="button"/>
</template>
```
And running a test like this:
```javascript
const wrapper = mount(Component, { props: { type: 'button' } })
const button = wrapper.find('[data-testid="button"]')
await button.trigger('click');
expect(wrapper.emitted()).toHaveProperty('something')
```

Does not work because the this.attributes().disabled (in Test Utils [baseWrapper](https://github.com/vuejs/test-utils/blob/main/src/baseWrapper.ts)) returns 'false' instead of undefined...

That means the dom was rendered incorrectly (`... disabled="false"` instead of not having disabled attribute).

**Comment by pkgray** [comment] 2022-10-04 14:41
@Ken-vdE Curious why this was closed and re-opened as a `vuejs/test-utils` issue - I only experience this when using `happy-dom` and not `jsdom`

**Comment by pkgray** [comment] 2022-10-13 14:27
> @pkgray you can view the mentioned issue above. There, more information is given.

When I switch back to jsdom, this issue is no longer a problem, so I think it is caused by happy-dom

**Comment by capricorn86** [comment] 2023-05-11 08:19
Thank you for reporting @Ken-vdE and @pkgray! :slightly_smiling_face: 

The issue has been fixed now.

You can read more about the release here:
https://github.com/capricorn86/happy-dom/releases/tag/v9.11.0

**Closed by capricorn86** 2023-05-11 08:19 UTC
Labels: bug, high priority
