### ISSUE TITLE
DOMParser is not defined

### ISSUE THREAD

**Issue by jgonte** [capricorn86/happy-dom#219] opened 2021-02-15 22:37 UTC
I am testing de-serializing an XML string into an object using jest and happy-dom

When I run the test I get:

ReferenceError: DOMParser is not defined

Code is below: 
switch(contentType) {
    case 'application/json': return JSON.parse(content);
    case 'application/xml': return (new DOMParser()).parseFromString(content, "text/xml");
          |                                                         ^
    default: return content;

Thanks :-)

**Comment by capricorn86** [comment] 2021-02-16 00:31
Hi @jgonte!

I am not exactly sure what the issue is here, but I have created two alternatives that I think should work :slightly_smiling_face: 

**Alternative 1 - Reference to DOMParser in Window**
```javascript
function parseContent(contentType, content) {
        const window = new AsyncWindow();

        switch(contentType) {
            case 'application/json': return JSON.parse(content);
            case 'application/xml': return (new window.DOMParser()).parseFromString(content, "text/xml");
        }
        
        return null;
}
```

**Alternative 2 - Run script with global scope as AsyncWindow**
```javascript
function parseContent(contentType, content) {
        const window = new AsyncWindow();
        
        VM.createContext(window);

        switch(contentType) {
            case 'application/json': return JSON.parse(content);
            case 'application/xml':
                 VM.runInContext('window.parsed = (new DOMParser()).parseFromString(`' + content + '`, "text/xml")', window);
                 return window.parsed;
        }
        
        return null;
}
```

**Comment by jgonte** [comment] 2021-02-17 12:56
Hi, thank you for your quick response.

My plan is to use this code in a browser.
Is there any way of accessing a global window reference so I don't need to come with these workarounds?

I am getting:

ReferenceError: AsyncWindow is not defined

      171 |
      172 |                     //@ts-ignore
    > 173 |                     const win = new AsyncWindow();
          |                           ^
      174 |
      175 |                     return (new win.DOMParser()).parseFromString(content, "text/xml");
      176 |                 }

________________________________

**Comment by capricorn86** [comment] 2021-02-17 15:57
Are you using some kind of bundler like Webpack? In that case you should be able to just import Window or AsyncWindow.

When Happy DOM is used in a browser it is recommended to use Window and not AsyncWindow, as AsyncWindow has references to server side packages.

```javascript
import { Window } from 'happy-dom';
```

If you want objects to be part of the browser global scope you will need to add the keys to the browser window object. However, this is not recommended as you will override the browser globals.

Using Node VM for creating a new global scope will not work in the browser.

If you wish to reuse he same code for both the browser and Happy DOM you can send in the window to the method.

```javascript
import { Window } from 'happy-dom';

function parseContent(win, contentType, content) {
        const window = new Window();

        switch(contentType) {
            case 'application/json': return JSON.parse(content);
            case 'application/xml': return (new win.DOMParser()).parseFromString(content, "text/xml");
        }
        
        return null;
}

// Parse with browser
parseContent(window, 'application/xml', '<content></content>');

// Parse with Happy DOM
parseContent(new AsyncWindow(), 'application/xml', '<content></content>');
```

It may be helpful to set global to be the window object for Happy DOM.

```javascript
window.global = window;
```

**Comment by capricorn86** [comment] 2021-02-17 15:58
AsyncWindow will most likely be removed in #218 and then you only need to import Window for both browser and server side.

**Comment by jgonte** [comment] 2021-02-17 22:24
Thank you again!

So, the import worked and I was able to use the typeof to select the appropriate window

import { Window } from 'happy-dom';


switch (contentType) {
                case 'application/json': return JSON.parse(content);
                case 'application/xml': {

                    let win;

                    if (typeof window !== "undefined") {

                        win = window;
                    }
                    else {

                        win = new Window();
                    }

                    return (new win.DOMParser()).parseFromString(content, "text/xml");
                }
                default: return content;
            }

When I run the test I get:

 The DOMParser in Happy DOM only supports the mime type "text/html".

      190 |                     }
      191 |
    > 192 |                     return (new win.DOMParser()).parseFromString(content, "text/xml");
          |                                                  ^
      193 |                 }
      194 |                 default: return content;
      195 |             }

And if I change to "text/html" I get an HTML Document which is expected but no XML

I understand that I am forcing the window object to do something it is not logical to do it

I should better find an XML serializer/deserializer in Javascript

But you can use the test to switch between happy-dom and the browser window if you find it useful

let win;

                    if (typeof window !== "undefined") {

                        win = window;
                    }
                    else {

                        win = new Window();
                    }

Thanks
Jorge

________________________________

**Comment by capricorn86** [comment] 2021-02-17 23:08
No problem! :slightly_smiling_face: 

It might be possible to add support for "text/xml" to Happy DOM.

What is it that you are trying to implement? You could also use the built in DOMParser in the browser if you are running this on the client side? :slightly_smiling_face:

**Comment by jgonte** [comment] 2021-02-18 16:55
You could do that but I just don't want to make you work on things that are kind of legacy such as XML serialization/deserialization, JSON is the standard now

I am implementing a Fetcher, an object that uses the fetch API to send and retrieve data from a server
So, I am trying to convert from XML string to Document and from there create a javascript object so the user of the library does need to not worry about doing that

I am planning to commit my latest changes this weekend but here is the link so far

https://github.com/jgonte/gclib-utils

Since this is the single use case for the DOM test environment so far, I am using jsdom for this one

Your wonderful testing environment I am using in this library because I need support for custom elements:

https://github.com/jgonte/gclib-vdom

Thanks
Jorge


________________________________

**Comment by capricorn86** [comment] 2021-02-22 20:21
@jgonte I have now added support for "text/xml" to DOMParser. I basically just added the new documents XMLDocument, SVGDocument and let the same parser that parses HTML parse XML as well, so it was easy to add support for it.

Hopefully it will work for you if you use it :slightly_smiling_face: 

Read more about the release here:
https://github.com/capricorn86/happy-dom/releases/tag/v2.7.0

**Comment by jgonte** [comment] 2021-02-24 20:56
Great!

Right now, I am not focused in XML deserialization since it seems legacy to me, but if the need arises .... 🙂

Also,

Did you have time to look to the links to the repositories I sent you? Any interest? 😅

Thank you
Jorge





________________________________

**Comment by capricorn86** [comment] 2021-02-26 23:15
Yes I have looked at it. Looks interesting, but I did not understand exactly what it does :sweat_smile:

**Comment by capricorn86** [comment] 2021-02-26 23:24
@jgonte can we close this issue? :slightly_smiling_face:

**Comment by jgonte** [comment] 2021-03-01 19:20
Yes

Thank you

________________________________

**Comment by jgonte** [comment] 2021-03-01 19:30
I am working on creating the next killer web components library [Animated GIF]

https://github.com/jgonte/gclib-wc
[https://avatars.githubusercontent.com/u/275388?s=400&v=4]<https://github.com/jgonte/gclib-wc>
jgonte/gclib-wc<https://github.com/jgonte/gclib-wc>
Web Components Library. Contribute to jgonte/gclib-wc development by creating an account on GitHub.
github.com


Is the library with the web components to use

The supporting libraries are

https://github.com/jgonte/gclib-utils

General patterns such as observer and subscriber, and utilities to facilitate posting receiving data, tracking changes, etc

 https://github.com/jgonte/gclib-vdom

Virtual DOM library to allow using JSX to generate the components in the render method

It is work in progress but I am having fun doing it 🤪 I will write some documentation once I have figured out the basic functionality

[Animated GIF]

Is one of the hardest projects I have ever done 😅


________________________________

**Comment by capricorn86** [comment] 2021-03-04 23:34
Sounds interesting! I hope you succeed :slightly_smiling_face:

**Closed** 2021-03-04 23:34 UTC
