### ISSUE TITLE
<img> tag loading property not implemented

### ISSUE THREAD

**Issue by totol123** [capricorn86/happy-dom#1311] opened 2024-03-14 19:17 UTC
**Describe the bug**

Working with : 
- happy-dom: 12.10.3
- vitest: 0.34.6
- vue: 3.4.3

I'm using <img loading="lazy"> API.

It raises a warning :
`[Vue warn]: Failed setting prop "loading" on <img>: value lazy is invalid. TypeError: Cannot set property loading of [object Object] which has only a getter`

and fail to put the attribute loading on the <img> (I checked on snapshot.)

I tried to switch to `jsdom` to compare and it works.

**To Reproduce**
1. Try to instantiate an <img loading="lazy"> with happy-dom

**Expected behavior**
Put the loading attribute to the <img>, causing no warning

**Additional context**
It's a quite implemented feature
![image](https://github.com/capricorn86/happy-dom/assets/43806574/72cb0b7e-67ec-4cb1-9a34-7abad8fc957e)

Thank you a lot for your work.
Anatole

**Comment by capricorn86** [comment] 2024-03-14 19:54
Thank you for reporting @totol123! :slightly_smiling_face: 

This was fixed in [v13.7.7](https://github.com/capricorn86/happy-dom/releases/tag/v13.7.7).

**Comment by capricorn86** [comment] 2024-03-14 19:54
Duplicate of #1218

**Closed by capricorn86** 2024-03-14 19:54 UTC
Labels: bug

**Comment by totol123** [comment] 2024-03-15 09:41
Oh I missed this, sorry for the dupplicate.
Thank you a lot.

Anatole
