### ISSUE TITLE
MutationObserver observe is not a function

### ISSUE THREAD

**Issue by CUBITECH** [capricorn86/happy-dom#1514] opened 2024-08-28 14:13 UTC
Hi,
in an Angular project, i have switched from JSDom to Happy Dom, for many reasons... I am using Jest as Testing Framework and jest-axe for a11y Tests. 
jest-axe uses MutationObserver for observing DOM changes, but the MutationObserver class in Happy Dom seems to work different(ly?).
After instantiating a MutationObserver the new object has no function 'observe', hence jest-axe throws an 'observer.observe is not a function' exception.

**To Reproduce**
1. In an Angular Project: Setup Jest as Testing Framework
2. Add jest-axe for a11y Tests
3. Add a test to an Angular component like described here https://www.npmjs.com/package/jest-axe "Testing Angular with nx"
4. Run Spec
5. axe-core throws observer.observe is not a function (Relevant code https://www.npmjs.com/package/axe-core?activeTab=code L:3555 - 3583)

**Expected behavior**
MutationObserver works as expected. 

Let me know if you need more information.

Thanks!

**Comment by capricorn86** [comment] 2024-08-28 23:59
Thank you for reporting @CUBITECH! :slightly_smiling_face: 

The instance method `observe()` is available in the `MutationObserver` in Happy DOM.

Example:
```javascript
`const observer = new MutationObserver((records) => {
	console.log(records);
})
observer.observe(element);
```

Do you have a repo or can you reproduce it in a test environment, so that we can debug what is causing the problem?

**Comment by CUBITECH** [comment] 2024-08-30 06:35
Hi, 

have build a StackBlitz: https://stackblitz.com/edit/happy-dom-issue-1514. 
Just run 'jest' in terminal.

**Comment by capricorn86** [comment] 2024-08-30 17:00
The problem seem to be that `zode.js` (which `jest-preset-angular` is using) patches several native classes with something that looks like this:
`{ __zone_symbol__originalInstance: MutationObserver {} }`

There is an issue for it here, but they don't seem to want to fix it:
https://github.com/angular/angular/issues/36460

The workaround seem to be to do:
```javascript
// @ts-ignore
window.MutationObserver = window[Zone.__symbol__("MutationObserver")];
```

My opinion is that it is a pretty bad idea to wrap the native classes, as no other libraries than Zone compatible libraries will work in this environment.

I will close this as this seem to be an issue with Angular and Zone.js and not Happy DOM.

**Closed by capricorn86** 2024-08-30 17:00 UTC
Labels: bug

**Comment by CUBITECH** [comment] 2024-09-01 08:02
Thanks for watching and the workaround!

**Comment by berkon** [comment] 2024-10-23 15:55
@capricorn86, could you please give some hints how exactly the workaround must be applied? When I'm putting it in a spec file or in the jest-setup.ts VSCode shows this error message when hovering over windo:

`Property 'prototype' is missing in type 'Window' but required in type '{ new (callback: MutationCallback): MutationObserver; prototype: MutationObserver; }'`

When replacing it with this, the error goes away:

`(window as any).MutationObserver = window[Zone.__symbol__("MutationObserver")];`

But then VSCode show this error when hovering over Zone:

`Cannot find name 'Zone'`

Importing and/or declaring Zone does not help either.

Thanks a lot for the workaround!

**Comment by CUBITECH** [comment] 2024-10-23 16:00
@berkon You need to annotate the line with  // @ts-ignore

**Comment by berkon** [comment] 2024-10-24 07:58
Thanks a lot @CUBITECH! That hint did the trick!
