### ISSUE TITLE
TypeError: window.XMLHttpRequest is not a constructor

### ISSUE THREAD

**Issue by quantuminformation** [capricorn86/happy-dom#553] opened 2022-07-27 13:05 UTC
I wonder if this might be missing too:
TypeError: window.XMLHttpRequest is not a constructor

**Comment by Mas0nShi** [comment] 2022-07-28 13:38
Duplicate of #463 

Hi @quantuminformation, 
I'm working on this feature,  See: #520
Of course, welcome PR if you can help us to implement it.

**Comment by capricorn86** [comment] 2022-12-07 16:04
Thanks for reporting @quantuminformation! 🙂 

We have now added support for XMLHttpRequest.

You can read more about the release here:
https://github.com/capricorn86/happy-dom/releases/tag/v7.8.0

**Closed by capricorn86** 2022-12-07 16:04 UTC
Labels: enhancement
