### ISSUE TITLE
Implement a node localName property

### ISSUE THREAD

**Issue by jgonte** [capricorn86/happy-dom#565] opened 2022-08-13 21:08 UTC
I think that node.localName is equivalent node.tagName?.toLowerCase() but I might be wrong

**Comment by capricorn86** [comment] 2022-10-14 13:37
Thanks for reporting @jgonte!

I believe that `Element.localName` is already supported or am I missing something? :sweat_smile:

**Comment by capricorn86** [comment] 2022-10-14 13:38
I will close this as I can't reproduce. Please re-open if I missed something.

**Closed by capricorn86** 2022-10-14 13:38 UTC

**Comment by jgonte** [comment] 2022-10-14 19:03
Maybe I need to update the library

Thank you and glad to hear from you, I thought the project was dead
________________________________
