### ISSUE TITLE
When using material UI with happy-dom/jest-environment, the deep merging fails

### ISSUE THREAD

**Issue by mramirarab** [capricorn86/happy-dom#419] opened 2022-03-16 15:13 UTC
I'm trying to make use of happy-dom in my project, however, I came across a problem that causes material UI elements to throw. Error looks something like the following:
![Screen Shot 2022-03-16 at 15 13 08](https://user-images.githubusercontent.com/33196628/158609606-7c9eba47-437e-4931-b985-bd8dbbb4d1b8.png)
After a long debugging session, I found out that material UI doesn't get the correct value for theme object. In material UI there is a check to see [if the object is a plain object](https://github.com/mui/material-ui/blob/master/packages/mui-utils/src/deepmerge.ts#L2). This equality returns true when the test-environment is jsdom and returns false when the environment is happy-dom.

**Comment by capricorn86** [comment] 2022-03-21 17:27
Thanks for reporting @mramirarab! :slightly_smiling_face: 

I assume that this only happens in the `@happy-dom/jest-environment` package? I can't reproduce it when using `happy-dom` directly.

In that case it has already been fixed and is a duplicate of #393.

You can read more about the release here:
https://github.com/capricorn86/happy-dom/releases/tag/v2.49.2

**Comment by capricorn86** [comment] 2022-03-21 17:28
Duplicate of #393

**Closed** 2022-03-22 15:44 UTC
Labels: bug, high priority
