### ISSUE TITLE
Incorrect DOM parsing with self-closing tags

### ISSUE THREAD

**Issue by yankouskia** [capricorn86/happy-dom#288] opened 2021-08-06 16:49 UTC
Hi!
I am trying to use the package for the custom parsing of DOM with custom component, but getting incorrect response for the markup with self-closing tags. Example:
```js
const { Window } = require('happy-dom');

const window = new Window();
const document = window.document;

document.body.innerHTML = `
<html>
  <head>
    <custom-attributes>
      <custom-accordion />
      <custom-accordion-element />
      <custom-accordion-text />
    </custom-attributes>
  </head>

  <body>
  </body>
</html>
`;

console.log(window.document.body.innerHTML);
```

Expected output:
```html
<html>
  <head>
    <custom-attributes>
      <custom-accordion></custom-accordion>
      <custom-accordion-element></custom-accordion-element>
      <custom-accordion-text></custom-accordion-text>
    </custom-attributes>
  </head>
  <body>
  </body>
</html>
```

Actual output:
```html
<html>
  <head>
    <custom-attributes>
      <custom-accordion>
      <custom-accordion-element>
      <custom-accordion-text>
    </custom-accordion-text>
  </custom-accordion-element>

  <body>
  </body>
</custom-accordion></custom-attributes></head></html>
```

**Comment by capricorn86** [comment] 2021-08-16 08:53
Thanks for reporting @yankouskia! :slightly_smiling_face: 

I will look into fixing it as soon as possible.

**Comment by yankouskia** [comment] 2021-09-30 13:53
Hey @capricorn86 is there some progress on that by chance?

**Comment by capricorn86** [comment] 2021-11-03 21:12
Hi @yankouskia! :slightly_smiling_face: 

Sorry taking such long time before taking this task. I am been very busy this summer and autumn.

I have added unit tests for this use case in the [latest version](https://github.com/capricorn86/happy-dom/compare/v2.24.2...v2.24.3#diff-c65a28f6db4e2a2f62d75fe160e0079cbee2bd6b3689ffbf18071efbdfa45f47), but I was not able to reproduce any bug. Are you using the latest version of Happy DOM?

**Comment by capricorn86** [comment] 2021-11-03 21:14
@tgilauri :point_up:

**Comment by capricorn86** [comment] 2021-12-21 00:34
I will close this for now as I can't reproduce it. Just re-open it if you still have the bug.

**Closed by capricorn86** 2021-12-21 00:34 UTC
Labels: bug
