### ISSUE TITLE
regression: assign of window.location.href

### ISSUE THREAD

**Issue by ilteoood** [capricorn86/happy-dom#678] opened 2022-12-10 15:05 UTC
**Describe the bug**

Starting with version 7.8.0, setting the `href` property like this:
```
window.location.href = '/foo'
```

Will throw an exception: `ERR_INVALID_URL`.

**To Reproduce**
1. Create a test with happy-dom
2. In the test, insert `window.location.href = '/foo'`
3. See error `ERR_INVALID_URL`

**Expected behavior**
I can set the `href` property using a string which doest not represent a full url, in the same exact way in which both chrome and firefox works.

**Screenshots**
<img width="548" alt="image" src="https://user-images.githubusercontent.com/6383527/206861764-f38db7fe-d3a8-4303-90a2-abd4cf6767ce.png">

**Device:**
 - OS: OS X
 - Browser: Vitest
 - Version: v0.25.6

**Additional context**
This happens using happy-dom during tests.

**Comment by Mas0nShi** [comment] 2022-12-16 10:24
copy that, the bug has reproduced.

**Comment by kalvenschraut** [comment] 2023-02-27 23:24
@capricorn86  Any idea when this or something similar to changing href/host/hostname of window.location would be landed?

Trying to use https://github.com/mswjs/msw and noticing a lot of odd behavior with it since window.location.host is an empty string with happy dom. Mainly it complains about invalid URLs when I try to use relative paths, which  works fine with [jsdom](https://github.com/mswjs/msw/issues/1415#issuecomment-1385196925)

Alternatively for my issue I would be fine with the default of location being something like `https://localhost` which is what I did locally to verify what was causing the issue,

**Comment by CSchulz** [comment] 2023-03-02 13:09
There is also an issue that the created url in RelativeURL isn't applicable to XHR requests.

Because the Location.href is not set (anymore):

```
Location {
  href: undefined,
  origin: 'http://localhost',
  protocol: 'http:',
  username: '',
  password: '',
  host: 'localhost',
  hostname: 'localhost',
  port: '',
  pathname: '/',
  search: '',
  searchParams: URLSearchParams {},
  hash: ''
}
```

**Closed** 2023-04-12 22:37 UTC
Labels: bug, high priority

**Comment by capricorn86** [comment] 2023-04-12 22:52
@ilteoood @kalvenschraut @CSchulz the particular issue of assigning a relative URL has been fixed. However, the default value is still set to "about:blank" and it is not possible to construct an absolute URL with as base "about:blank".

Big thanks to @Mas0nShi for your contribution! :star2: 

You can read more about the release here:

**Comment by capricorn86** [comment] 2023-04-12 22:54
**Regarding the default URL "about:blank":**

There are some open questions that has to be resolved:

1. What would that URL be in that case? There is for example a big difference between "https://localhost" and "http://localhost".
2. Is it really secure to set another default value? Requests will contain it as referrer and CORS requests will be validated towards it.

I'm happy to change the default value if we can find a solution to these questions :slightly_smiling_face:

We should open a new ticket for it in that case.

**Comment by kalvenschraut** [comment] 2023-04-13 03:30
https://github.com/jsdom/jsdom/blob/47ec32174149097fdb296f96a6e5db0ca92c6093/test/api/options.js#L65

I found above test so it looks like jsdom does about:blank also.

I am find with that as a default as long we I could change it to what I need in a global setup file before I run my tests. Which with this issue being closed sounds like I can do so now. Will verify that I can likely next week sometime once I get around to updating packages again.

**Comment by aligneddev** [comment] 2023-07-25 21:05
I ran into this with msw 1.2.3 (see https://github.com/mswjs/msw/issues/1415).
@SiongSng's commit linked above helped me.

in my vitest.setup.ts I set location.href = 'https://www.myurl.com/' and the error went away
